# -*- coding: utf-8 -*-
"""تشخیص سرطان سینه.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IW8ADvWCAoM9-6CKxOC-i9rKzjFThtbn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("cancer.csv")

data.head(10)

data.info()

data=data.drop(['Unnamed: 32', 'id'], axis = 1)
data.diagnosis = [1 if each == "M" else 0 for each in data.diagnosis]

y = data.diagnosis
x_data = data.drop(['diagnosis'], axis = 1)

x_data=np.array([0,10.0,20.0,40.0])

x = (x_data - np.min(x_data))/(np.max(x_data) - np.min(x_data))

x

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.15, random_state = 42)

# x_train = x_train.T
# x_test = x_test.T
# y_train = y_train.T
# y_test = y_test.T

print("x train: ", x_train.shape)
print("x test: ", x_test.shape)
print("y train: ", y_train.shape)
print("y test: ", y_test.shape)

from sklearn import linear_model
robot = linear_model.LogisticRegression()

robot.max_iter=1000000
robot.fit(x_train, y_train)

t=robot.predict(x_test)
v= y_test ==t
v=v.reset_index()
v=v.diagnosis
n=0
for i in v:
    if i==False : n=n+1

print(n,'/',len(v))